package Vista;

import Controlador.Controller;
import javax.swing.*;
import Modelo.*;

public class Interfaz extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame
	 */
	DefaultListModel<String> actors;
	private Controller cont;
	public Interfaz() {
		initComponents();
		actors= new DefaultListModel<>();
		cont= new Controller();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		TipoActor = new javax.swing.ButtonGroup();
		TipoDecorador = new javax.swing.ButtonGroup();
		TipoMessage = new javax.swing.ButtonGroup();
		CrearActor = new javax.swing.JButton();
		Decorador = new javax.swing.JToggleButton();
		Message = new javax.swing.JButton();
		Quepasa = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList<>();
		numReal = new javax.swing.JTextField();
		NumeroActores = new javax.swing.JLabel();
		MessageText = new javax.swing.JTextField();
		Actorname = new javax.swing.JTextField();
		Decorator = new javax.swing.JRadioButton();
		Encrypt = new javax.swing.JRadioButton();
		Lambda = new javax.swing.JRadioButton();
		RingActor = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		MessageT = new javax.swing.JRadioButton();
		AddInsultMessage = new javax.swing.JRadioButton();
		GetAllInsult = new javax.swing.JRadioButton();
		QuitMessage = new javax.swing.JRadioButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		TipoActor.add(RingActor);
		RingActor.setText("RingActor");
		RingActor.setActionCommand("RingActor");

		TipoActor.add(jRadioButton2);
		jRadioButton2.setText("PingPong");
		jRadioButton2.setActionCommand("PingPong");

		TipoActor.add(jRadioButton3);
		jRadioButton3.setText("InsultActor");
		jRadioButton3.setActionCommand("InsultActor");



		TipoDecorador.add(Decorator);
		Decorator.setText("Decorador");
		Decorator.setActionCommand("Decorator");

		TipoDecorador.add(Encrypt);
		Encrypt.setText("Encrypt");
		Encrypt.setActionCommand("Encrypt");

		TipoDecorador.add(Lambda);
		Lambda.setText("Lambda");
		Lambda.setActionCommand("Lambda");


		TipoMessage.add(MessageT);
		MessageT.setText("MessageT");
		MessageT.setActionCommand("MessageT");

		TipoMessage.add(AddInsultMessage);
		AddInsultMessage.setText("AddInsultMessage");
		AddInsultMessage.setActionCommand("AddInsultMessage");

		TipoMessage.add(QuitMessage);
		QuitMessage.setText("QuitMessage");
		QuitMessage.setActionCommand("QuitMessage");

		TipoMessage.add(GetAllInsult);
		GetAllInsult.setText("GetAllInsult");
		GetAllInsult.setActionCommand("GetAllInsult");



		CrearActor.setText("Crear Actor");
		CrearActor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					CrearActorActionPerformed(evt);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});

		Decorador.setText("Decorador");
		Decorador.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					DecoradorActionPerformed(evt);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		});

		Message.setText("Message");
		Message.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				MessageActionPerformed(evt);
			}
		});

		Quepasa.setViewportView(jList1);

		NumeroActores.setText("Numero de actores");

		Decorator.setText("Decorator");

		Encrypt.setText("Encrypt");

		Lambda.setText("Lambda");

		RingActor.setText("RingActor");

		jRadioButton2.setText("PingPong");

		jRadioButton3.setText("InsultActor");

		MessageT.setText("MessageT");

		AddInsultMessage.setText("AddInsultMessage");

		GetAllInsult.setText("GetAllInsult");

		QuitMessage.setText("QuitMessage");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(Quepasa)
								.addGap(109, 109, 109))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGap(150, 150, 150)
								.addComponent(NumeroActores)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGap(54, 54, 54)
												.addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(31, 31, 31)
												.addComponent(MessageText, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup()
												.addGap(22, 22, 22)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(Actorname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(RingActor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(MessageT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup()
																				.addGap(57, 57, 57)
																				.addComponent(numReal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(layout.createSequentialGroup()
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(AddInsultMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(GetAllInsult, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addComponent(CrearActor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Decorador, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(QuitMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
												.addGap(0, 17, Short.MAX_VALUE)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(Decorator, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Encrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Lambda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(71, 71, 71))))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGap(58, 58, 58)
																.addComponent(NumeroActores))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(Decorador)))
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGap(18, 18, 18)
																.addComponent(numReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addComponent(Decorator)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Encrypt)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(Lambda)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
										.addGroup(layout.createSequentialGroup()
												.addGap(24, 24, 24)
												.addComponent(CrearActor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18)
												.addComponent(Actorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(16, 16, 16)
												.addComponent(RingActor)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jRadioButton2)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
								.addComponent(jRadioButton3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Message)
										.addComponent(MessageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(MessageT)
										.addComponent(AddInsultMessage)
										.addComponent(GetAllInsult)
										.addComponent(QuitMessage))
								.addGap(4, 4, 4)
								.addComponent(Quepasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(286, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>

	private void CrearActorActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {
		if(TipoActor.getSelection()!=null){
			cont.crearActor(actors,Actorname.getText(),TipoActor.getSelection().getActionCommand(),Integer.valueOf(numReal.getText()));
			Thread.sleep(100);
			String[] names= cont.listNames(actors);
			jList1.setListData(names);
		}
	}

	private void DecoradorActionPerformed(java.awt.event.ActionEvent evt) throws InterruptedException {
		if(TipoDecorador.getSelection()!=null) {
			actors.addElement(cont.decoratorType(TipoDecorador.getSelection().getActionCommand(), Actorname.getText()));
			Thread.sleep(100);
			String[] names = cont.listNames(actors);
			jList1.setListData(names);
		}
	}

	private void MessageActionPerformed(java.awt.event.ActionEvent evt) {
		if(TipoDecorador.getSelection()!=null && 	jList1.getSelectedValue()!=null ) {
			String name = jList1.getSelectedValue().split(" ")[0];
			cont.sendMessage(name, MessageT.getText(),  MessageText.getText());
		}
	}


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Interfaz().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JTextField Actorname;
	private javax.swing.JRadioButton AddInsultMessage;
	private javax.swing.JButton CrearActor;
	private javax.swing.JToggleButton Decorador;
	private javax.swing.JRadioButton Decorator;
	private javax.swing.JRadioButton Encrypt;
	private javax.swing.JRadioButton GetAllInsult;
	private javax.swing.JRadioButton Lambda;
	private javax.swing.JButton Message;
	private javax.swing.JRadioButton MessageT;
	private javax.swing.JTextField MessageText;
	private javax.swing.JLabel NumeroActores;
	private javax.swing.JScrollPane Quepasa;
	private javax.swing.JRadioButton QuitMessage;
	private javax.swing.JRadioButton RingActor;
	private javax.swing.ButtonGroup TipoActor;
	private javax.swing.ButtonGroup TipoDecorador;
	private javax.swing.ButtonGroup TipoMessage;
	private javax.swing.JList<String> jList1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JTextField numReal;
	// End of variables declaration
}
